In [44]:
import pandas as pd #create and save datasets
import numpy as np #Statistical calculations
from faker import Faker #generate realistic fake data
import random #generate random values
from pathlib import Path #create file paths

# Create Faker object
fake = Faker()
Faker.seed(42)
random.seed(42)

# Configuration

BASE_PATH = Path("../data/raw")
PLM_PATH = BASE_PATH / "plm"
MES_PATH = BASE_PATH / "mes"

NUM_PRODUCTS = 100
NUM_ORDERS = 1000
NUM_MACHINE_LOGS = 10000
NUM_DOWNTIME_EVENTS = 300
NUM_ECNR = 150

In [6]:
# Number of Products
NUM_PRODUCTS = 100
product_names = ["Gear Box", "Drive Shaft", "Bearing Housing", "Brake Disc", "Clutch Plate",
"Engine Block", "Cylinder Head", "Axle Shaft", "Pulley", "Rotor",
"Stator", "Control Panel", "Hydraulic Pump", "Valve Body", "Bearing",
"Coupling", "Flywheel", "Crankshaft", "Piston", "Camshaft",
"Oil Pump", "Fuel Injector", "Timing Belt", "Cooling Fan", "Radiator",
"Air Filter", "Exhaust Manifold", "Turbocharger", "Starter Motor", "Alternator",
"Wheel Hub", "Steering Knuckle", "Suspension Arm", "Brake Caliper", "Shock Absorber",
"Transmission Case", "Differential Gear", "Planetary Gear", "Universal Joint", "Seal Ring",
"O-Ring", "Flange", "Fastener Kit", "Hex Bolt", "Lock Nut",
"Washer Plate", "Sprocket", "Chain Drive", "Roller Bearing", "Linear Guide",
"Servo Motor", "Stepper Motor", "PLC Module", "Sensor Module", "Pressure Sensor",
"Temperature Sensor", "Flow Meter", "Solenoid Valve", "Actuator", "Control Valve",
"Hydraulic Cylinder", "Pneumatic Cylinder", "Compressor Unit", "Vacuum Pump", "Heat Exchanger",
"Boiler Tube", "Conveyor Roller", "Conveyor Belt", "Mixer Blade", "Impeller",
"Filter Housing", "Nozzle", "Manifold Block", "Connector", "Terminal Block",
"Fuse Box", "Power Supply Unit", "Transformer Core", "Cooling Jacket", "Fan Blade",
"Motor Shaft", "Housing Cover", "Gear Wheel", "Rack Gear", "Pinion Gear",
"Guide Rail", "Support Bracket", "Mounting Plate", "Clamp", "Hinge Assembly",
"Door Frame", "Chassis Frame", "Base Plate", "Machine Guard", "Inspection Cover",
"Lubrication Unit", "Tool Holder", "Cutting Head", "Spindle Assembly", "Fixture Plate"]

materials = ["Steel","Stainless Steel","Cast Iron","Aluminium","Copper","Brass","Titanium","Carbon Steel","Alloy Steel","Plastic",
"Rubber", "Ceramic"]

categories = [
    "Engine",
    "Transmission",
    "Hydraulic",
    "Electrical",
    "Mechanical",
    "Braking",
    "Suspension",
    "Pneumatic",
    "Cooling",
    "Automation"
]

status = [
    "Released",
    "Prototype",
    "In Review",
    "Obsolete"
]

versions = ["V1.0","V1.1","V1.2","V2.0","V2.1","V2.2","V3.0"]

In [23]:
product_data = []

for i in range(1, NUM_PRODUCTS + 1):

    product = {
        "product_id": f"P{i:03}",
        "product_name": product_names[i-1],          # Unique product names
        "design_release_date": fake.date_between(
            start_date="-3y",
            end_date="today"
        ),
        "CAD_file_ref": f"CAD{i:05}",
        "product_version": random.choice(versions),
        "material": random.choice(materials),
        "product_category": random.choice(categories),
        "lifecycle_status": random.choices(
            status,
            weights=[70,15,10,5],
            k=1
        )[0]
    }

    product_data.append(product)

product_df = pd.DataFrame(product_data)

In [24]:
from pathlib import Path
output_path = Path("../data/raw/plm")
output_path.mkdir(parents=True, exist_ok=True)

product_df.to_csv(
    output_path / "product_metadata.csv",
    index=False
)
print("✅ product_metadata.csv created successfully!")
print(product_df.head())

✅ product_metadata.csv created successfully!
  product_id     product_name design_release_date CAD_file_ref  \
0       P001         Gear Box          2026-04-12     CAD00001
1       P002      Drive Shaft          2024-01-12     CAD00002
2       P003  Bearing Housing          2023-08-31     CAD00003
3       P004       Brake Disc          2024-09-23     CAD00004
4       P005     Clutch Plate          2024-08-07     CAD00005

  product_version         material product_category lifecycle_status
0            V2.2  Stainless Steel           Engine        Prototype
1            V1.1        Aluminium        Hydraulic        Prototype
2            V2.2          Ceramic          Cooling         Released
3            V2.0            Steel           Engine         Released
4            V1.1      Alloy Steel       Automation         Released

In [12]:
display(product_df)

,product_id,product_name,design_release_date,CAD_file_ref,product_version,material,product_category,lifecycle_status
0,P001,Gear Box,2023-10-18,CAD00001,V2.0,Cast Iron,Engine,Released
1,P002,Drive Shaft,2024-07-13,CAD00002,V3.0,Steel,Braking,Released
2,P003,Bearing Housing,2023-09-11,CAD00003,V1.1,Rubber,Transmission,Released
3,P004,Brake Disc,2024-11-25,CAD00004,V2.1,Titanium,Automation,Prototype
4,P005,Clutch Plate,2025-04-07,CAD00005,V1.1,Cast Iron,Hydraulic,In Review
...,...,...,...,...,...,...,...,...
95,P096,Lubrication Unit,2025-10-28,CAD00096,V2.1,Aluminium,Transmission,Released
96,P097,Tool Holder,2024-02-04,CAD00097,V2.0,Carbon Steel,Cooling,Prototype
97,P098,Cutting Head,2024-02-08,CAD00098,V2.2,Carbon Steel,Pneumatic,Released
98,P099,Spindle Assembly,2026-05-13,CAD00099,V1.0,Stainless Steel,Mechanical,Released
99,P100,Fixture Plate,2025-07-31,CAD00100,V2.2,Aluminium,Mechanical,Released

In [13]:
# Read Product Metadata 
product_df = pd.read_csv("../data/raw/plm/product_metadata.csv")
product_df.head()

,product_id,product_name,design_release_date,CAD_file_ref,product_version,material,product_category,lifecycle_status
0,P001,Gear Box,2023-10-18,CAD00001,V2.0,Cast Iron,Engine,Released
1,P002,Drive Shaft,2024-07-13,CAD00002,V3.0,Steel,Braking,Released
2,P003,Bearing Housing,2023-09-11,CAD00003,V1.1,Rubber,Transmission,Released
3,P004,Brake Disc,2024-11-25,CAD00004,V2.1,Titanium,Automation,Prototype
4,P005,Clutch Plate,2025-04-07,CAD00005,V1.1,Cast Iron,Hydraulic,In Review

In [14]:
#BOM
component_names = [
    "Bearing",
    "Shaft",
    "Housing",
    "Seal Ring",
    "Bolt",
    "Nut",
    "Washer",
    "Rotor",
    "Stator",
    "Gear",
    "Pulley",
    "Valve",
    "Sensor",
    "Motor",
    "Coupling",
    "Spring",
    "Clamp",
    "Bracket",
    "Pipe",
    "Nozzle",
    "Filter",
    "Impeller",
    "Gasket",
    "Connector",
    "Cable"
]

suppliers = [
    "SKF",
    "Bosch",
    "Siemens",
    "Timken",
    "Tata Steel",
    "L&T",
    "ABB",
    "Honeywell",
    "Schneider Electric",
    "Crompton"
]

units = ["Nos", "Kg", "Meter"]

In [15]:
bom_data = []

component_counter = 1

for product in product_df["product_id"]:

    num_components = random.randint(5, 10)

    selected_components = random.sample(component_names, num_components)

    for component in selected_components:

        bom_data.append({
            "product_id": product,
            "component_id": f"C{component_counter:04}",
            "component_name": component,
            "quantity": random.randint(1, 10),
            "unit": random.choice(units),
            "supplier": random.choice(suppliers)
        })

        component_counter += 1

In [16]:
bom_df = pd.DataFrame(bom_data)

bom_df.head()

  product_id component_id component_name  quantity   unit            supplier
0       P001        C0001         Spring         6  Meter           Honeywell
1       P001        C0002        Bracket         5     Kg          Tata Steel
2       P001        C0003          Clamp         4    Nos              Timken
3       P001        C0004          Valve         6    Nos  Schneider Electric
4       P001        C0005          Motor         3    Nos              Timken

In [17]:
bom_df.to_csv(
    "../data/raw/plm/bom.csv",
    index=False
)

print("✅ bom.csv created successfully!")
print("Rows:", len(bom_df))
print(bom_df.head())

✅ bom.csv created successfully!
Rows: 744
  product_id component_id component_name  quantity   unit            supplier
0       P001        C0001         Spring         6  Meter           Honeywell
1       P001        C0002        Bracket         5     Kg          Tata Steel
2       P001        C0003          Clamp         4    Nos              Timken
3       P001        C0004          Valve         6    Nos  Schneider Electric
4       P001        C0005          Motor         3    Nos              Timken

In [13]:
product_df = pd.read_csv("../data/raw/plm/product_metadata.csv")

In [14]:
change_types = [
    "Design Update",
    "Material Change",
    "Dimension Change",
    "Quality Improvement",
    "Cost Reduction",
    "Safety Enhancement",
    "Performance Improvement",
    "Supplier Change"
]

priorities = [
    "Low",
    "Medium",
    "High",
    "Critical"
]

status_list = [
    "Open",
    "In Progress",
    "Approved",
    "Rejected",
    "Closed"
]

engineers = [
    "Rahul Sharma",
    "Priya Nair",
    "Ankit Verma",
    "Sneha Rao",
    "Arjun Patel",
    "Meera Iyer",
    "Kiran Kumar",
    "Vivek Joshi"
]

In [15]:
ecnr_data = []

for i in range(1, 151):

    product = random.choice(product_df["product_id"])

    row = {
        "ecnr_id": f"ECNR{i:04}",
        "product_id": product,
        "request_date": fake.date_between(
            start_date="-2y",
            end_date="today"
        ),
        "change_type": random.choice(change_types),
        "priority": random.choices(
            priorities,
            weights=[20, 40, 30, 10],
            k=1
        )[0],
        "status": random.choice(status_list),
        "requested_by": random.choice(engineers)
    }

    ecnr_data.append(row)

In [16]:
ecnr_df = pd.DataFrame(ecnr_data)

ecnr_df.head()

,ecnr_id,product_id,request_date,change_type,priority,status,requested_by
0,ECNR0001,P048,2025-09-23,Supplier Change,Medium,Approved,Kiran Kumar
1,ECNR0002,P096,2024-11-28,Safety Enhancement,Medium,Rejected,Arjun Patel
2,ECNR0003,P040,2025-02-13,Cost Reduction,Medium,In Progress,Meera Iyer
3,ECNR0004,P016,2025-09-05,Dimension Change,Low,Rejected,Arjun Patel
4,ECNR0005,P093,2026-05-31,Cost Reduction,Critical,In Progress,Arjun Patel

In [21]:
ecnr_df.to_csv("../data/raw/plm/ecnr_requests.csv",
    index=False
)
print("ECNR dataset created successfully!")
print("Total Records :", len(ecnr_df))

ECNR dataset created successfully!
Total Records : 150

In [18]:
ecnr_df.shape

(150, 7)

In [27]:
machine_ids = ["MC001","MC002","MC003","MC004","MC005",
"MC006","MC007","MC008","MC009","MC010"]
shifts = ["Morning","Evening","Night"]
machine_status = ["Running","Idle","Maintenance"]

In [28]:
machine_logs = []

for i in range(10000):

    product = random.choice(product_df["product_id"])

    status = random.choices(
        machine_status,
        weights=[80, 15, 5],
        k=1
    )[0]

    if status == "Running":
        output_qty = random.randint(40, 120)
        defect_qty = random.randint(0, 5)
    elif status == "Idle":
        output_qty = 0
        defect_qty = 0
    else:
        output_qty = random.randint(0, 10)
        defect_qty = random.randint(0, 2)

    row = {
        "machine_id": random.choice(machine_ids),
        "timestamp": fake.date_time_between(
            start_date="-90d",
            end_date="now"
        ),
        "product_id": product,
        "shift": random.choice(shifts),
        "temperature": round(random.uniform(25, 90), 2),
        "pressure": round(random.uniform(80, 150), 2),
        "cycle_time_sec": round(random.uniform(20, 90), 2),
        "output_qty": output_qty,
        "defect_qty": defect_qty,
        "machine_status": status
    }

    machine_logs.append(row)

In [29]:
machine_df = pd.DataFrame(machine_logs)

machine_df.head()

,machine_id,timestamp,product_id,shift,temperature,pressure,cycle_time_sec,output_qty,defect_qty,machine_status
0,MC004,2026-06-26 17:14:36,P082,Morning,72.87,127.37,82.45,75,1,Running
1,MC002,2026-05-06 10:41:28,P012,Morning,40.12,122.14,59.29,44,0,Running
2,MC004,2026-04-28 01:33:01,P092,Evening,63.30,136.66,20.45,109,3,Running
3,MC003,2026-07-06 15:12:32,P021,Morning,87.22,103.56,26.49,83,2,Running
4,MC005,2026-05-22 08:08:09,P013,Morning,72.43,117.54,88.12,84,4,Running

In [30]:
machine_df.to_csv(
    "../data/raw/mes/machine_logs.csv",
    index=False
)

print("Machine Logs Created Successfully!")
print("Total Records :", len(machine_df))

Machine Logs Created Successfully!
Total Records : 10000

In [32]:
print(machine_df.shape)
print()
print(machine_df.isnull().sum())
print()
print(machine_df["machine_status"].value_counts())
print()
print(machine_df.head())

(10000, 10)

machine_id        0
timestamp         0
product_id        0
shift             0
temperature       0
pressure          0
cycle_time_sec    0
output_qty        0
defect_qty        0
machine_status    0
dtype: int64

machine_status
Running        7950
Idle           1534
Maintenance     516
Name: count, dtype: int64

  machine_id           timestamp product_id    shift  temperature  pressure  \
0      MC004 2026-06-26 17:14:36       P082  Morning        72.87    127.37
1      MC002 2026-05-06 10:41:28       P012  Morning        40.12    122.14
2      MC004 2026-04-28 01:33:01       P092  Evening        63.30    136.66
3      MC003 2026-07-06 15:12:32       P021  Morning        87.22    103.56
4      MC005 2026-05-22 08:08:09       P013  Morning        72.43    117.54

   cycle_time_sec  output_qty  defect_qty machine_status
0           82.45          75           1        Running
1           59.29          44           0        Running
2           20.45         109           3        Running
3           26.49          83           2        Running
4           88.12          84           4        Running

In [40]:
# Products that are ordered more frequently
popular_products = [
    "P001", "P002", "P003", "P004", "P005",
    "P006", "P007", "P008", "P009", "P010"
]

# Machine capacities
machine_capacity = {
    "MC001": 120,
    "MC002": 110,
    "MC003": 100,
    "MC004": 90,
    "MC005": 95,
    "MC006": 85,
    "MC007": 80,
    "MC008": 75,
    "MC009": 70,
    "MC010": 65
}

# Customers and their typical order quantity
customer_data = {
    "Bosch": (700, 1200),
    "Toyota": (600, 1000),
    "Tata Motors": (500, 900),
    "Mahindra": (400, 800),
    "Ashok Leyland": (350, 750),
    "TVS": (200, 600),
    "Hyundai": (450, 850),
    "Honda": (300, 700),
    "Volvo": (300, 700),
    "Bharat Benz": (350, 750)
}

order_status = [
    "Completed",
    "In Progress",
    "Scheduled",
    "Cancelled"
]

In [39]:
orders = []

for i in range(1, 1001):

    # Popular products appear more often
    if random.random() < 0.60:
        product_id = random.choice(popular_products)
    else:
        product_id = random.choice(product_df["product_id"].tolist())

    product = product_df[product_df["product_id"] == product_id].iloc[0]

    # Customer
    customer = random.choice(list(customer_data.keys()))

    min_qty, max_qty = customer_data[customer]

    planned_qty = random.randint(min_qty, max_qty)

    # Machine
    machine = random.choice(list(machine_capacity.keys()))

    capacity = machine_capacity[machine]

    produced_qty = random.randint(
        int(planned_qty * 0.90),
        planned_qty
    )

    rejected_qty = round(
        produced_qty * random.uniform(0.005, 0.03)
    )

    efficiency = round(
        (produced_qty / planned_qty) * 100,
        2
    )

    orders.append({
        "order_id": f"PO{i:05}",
        "product_id": product["product_id"],
        "product_name": product["product_name"],
        "customer": customer,
        "machine_id": machine,
        "order_date": fake.date_between(
            start_date="-6M",
            end_date="today"
        ),
        "planned_quantity": planned_qty,
        "produced_quantity": produced_qty,
        "rejected_quantity": rejected_qty,
        "efficiency_percent": efficiency,
        "order_status": random.choices(
            order_status,
            weights=[65,20,10,5],
            k=1
        )[0]
    })

In [41]:
production_orders = pd.DataFrame(orders)

production_orders.head()

,order_id,product_id,product_name,machine_id,customer,order_date,planned_quantity,produced_quantity,rejected_quantity,order_status
0,PO00001,P073,Manifold Block,MC002,Toyota,2026-04-12,925,844,12,Completed
1,PO00002,P085,Pinion Gear,MC009,Volvo,2026-07-20,907,855,20,Completed
2,PO00003,P017,Flywheel,MC001,Tata Motors,2026-07-04,705,683,10,Completed
3,PO00004,P031,Wheel Hub,MC010,Volvo,2026-03-27,664,620,19,In Progress
4,PO00005,P077,Power Supply Unit,MC002,Toyota,2026-06-10,816,653,1,Completed

In [42]:
production_orders.to_csv(
    "../data/raw/mes/production_orders.csv",
    index=False
)

print("production_orders.csv created successfully")
print("Total Orders :", len(production_orders))

production_orders.csv created successfully
Total Orders : 1000

In [43]:
#To verify data
print(production_orders.shape)
print()

print(production_orders.head())
print()

print(production_orders["order_status"].value_counts())
print()

print(production_orders["customer"].value_counts())

(1000, 10)

  order_id product_id       product_name machine_id     customer  order_date  \
0  PO00001       P073     Manifold Block      MC002       Toyota  2026-04-12
1  PO00002       P085        Pinion Gear      MC009        Volvo  2026-07-20
2  PO00003       P017           Flywheel      MC001  Tata Motors  2026-07-04
3  PO00004       P031          Wheel Hub      MC010        Volvo  2026-03-27
4  PO00005       P077  Power Supply Unit      MC002       Toyota  2026-06-10

   planned_quantity  produced_quantity  rejected_quantity order_status
0               925                844                 12    Completed
1               907                855                 20    Completed
2               705                683                 10    Completed
3               664                620                 19  In Progress
4               816                653                  1    Completed

order_status
Completed      687
In Progress    182
Scheduled       79
Cancelled       52
Name: count, dtype: int64

customer
Honda            115
Volvo            108
Toyota           107
Hyundai          105
Ashok Leyland    104
Tata Motors      101
Mahindra          97
Bharat Benz       89
TVS               87
Bosch             87
Name: count, dtype: int64

In [45]:
#downtime_events.csv
machine_failure_weight = {
    "MC001": 3,
    "MC002": 5,
    "MC003": 6,
    "MC004": 8,
    "MC005": 4,
    "MC006": 9,
    "MC007": 7,
    "MC008": 3,
    "MC009": 2,
    "MC010": 1
}

reasons = [
    "Machine Breakdown",
    "Preventive Maintenance",
    "Power Failure",
    "Tool Change",
    "Quality Inspection",
    "Operator Unavailable",
    "Material Shortage",
    "Sensor Failure"
]

status = [
    "Resolved",
    "Pending",
    "In Progress"
]

technicians = [
    "Ramesh",
    "Suresh",
    "Anil",
    "Kiran",
    "Rahul",
    "Meena",
    "Priya",
    "Asha"
]

In [46]:
downtime = []

for i in range(1, 301):

    machine = random.choices(
        list(machine_failure_weight.keys()),
        weights=machine_failure_weight.values(),
        k=1
    )[0]

    duration = random.randint(10, 180)

    downtime.append({
        "event_id": f"DT{i:04}",
        "machine_id": machine,
        "event_date": fake.date_between(
            start_date="-6M",
            end_date="today"
        ),
        "reason": random.choice(reasons),
        "downtime_minutes": duration,
        "technician": random.choice(technicians),
        "status": random.choice(status)
    })

In [48]:
downtime_df = pd.DataFrame(downtime)

downtime_df.head()
downtime_df.to_csv(
    "../data/raw/mes/downtime_events.csv",
    index=False
)

print("downtime_events.csv created successfully")
print("Total Records :", len(downtime_df))

downtime_events.csv created successfully
Total Records : 300

In [49]:
print(downtime_df.shape)
print()

print(downtime_df.head())
print()

print(downtime_df["reason"].value_counts())
print()

print(downtime_df["machine_id"].value_counts())

(300, 7)

  event_id machine_id  event_date                  reason  downtime_minutes  \
0   DT0001      MC006  2026-05-26      Quality Inspection                16
1   DT0002      MC002  2026-02-12  Preventive Maintenance                36
2   DT0003      MC001  2026-01-26             Tool Change                65
3   DT0004      MC003  2026-06-14       Material Shortage               176
4   DT0005      MC006  2026-03-16           Power Failure                11

  technician       status
0      Kiran     Resolved
1      Priya     Resolved
2     Ramesh  In Progress
3      Kiran      Pending
4      Priya      Pending

reason
Operator Unavailable      46
Power Failure             45
Preventive Maintenance    41
Tool Change               39
Sensor Failure            38
Material Shortage         37
Machine Breakdown         29
Quality Inspection        25
Name: count, dtype: int64

machine_id
MC006    62
MC003    51
MC004    49
MC007    40
MC002    34
MC005    21
MC008    17
MC001    12
MC010     7
MC009     7
Name: count, dtype: int64

NameError: name 'PLM_PATH' is not defined